105 Header
fga-eps-mds/2023.2-UnB-TV-Frontend pull request #14
Opened 2023-11-15 22:01 UTC by savioc2

Adiciona funcionalidades aos botões do header

2023-11-16 15:48 UTC, joao15victor08 requested changes

2023-11-16 15:48 UTC, joao15victor08 commented on src/app/app-routing.module.ts
> +  { path: 'transmissoes', component: TransmissoesComponent}
Componentes desnecessários. Já existe os componentes ou ainda estão em desenvolvimento.

2023-11-16 15:48 UTC, joao15victor08 commented on src/app/app.module.ts
> +import { ProgramacaoComponent } from './pages/programacao/programacao.component';
Componentes desnecessários. Já existe os componentes ou ainda estão em desenvolvimento.

2023-11-16 15:48 UTC, joao15victor08 commented on src/app/app.module.ts
> +    ProgramacaoComponent,
Componentes desnecessários. Já existe os componentes ou ainda estão em desenvolvimento.

2023-11-16 15:48 UTC, joao15victor08 commented on src/app/components/background/background.component.html
> +              <a routerLink="/transmissoes" class="pl-2">Transmissões</a>
Redirecionar para os componentes já existentes, caso não exista ainda redirecione para "".
Inicio não existe mais.
Agora na Tv para o componente streamView (Ainda em desenvolvimento).
Programação para o componente grid days (Ainda em desenvolvimento).
Transmissoes não existe.
Falta o Participe que redireciona para o componente participate.
Falta o Catálogo que redireciona para o componente video.

2023-11-16 15:48 UTC, joao15victor08 commented on src/app/components/background/background.component.html
> +          <a class="menu-item">teste</a>
Acrecentar apenas opção perfil que redireciona para o componente profile

2023-11-17 20:39 UTC, DaviMarinho approved these changes
LGTM!

2023-11-17 20:39 UTC, joao15victor08 approved these changes

2023-11-17 20:40 UTC, merged